### ISSUE TITLE
User-specific Favourites

### ISSUE THREAD

**Issue by sch-mar** [sch-mar/TooGoodToGo-Bot#5]
The bot notifies each user based on his favourites, so he can customise his notifications through the tgtg app.

- [x] setup procedure (mainly for user-specific credentials)
    - [x] fix login
- [x] db solution

**Comment by sch-mar** [comment]
**db solution:**
YAML files in ```data/```

---

idea for ```users.yaml```

```yaml
<internal_user_id>:
    name: <name>
    chat_id: <chat_id>
    language: <language>
    ...
<internal_user_id>:
    name: <name>
    chat_id: <chat_id>
    language: <language>
    ...
...
```
